version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
  logs:
